matrix:
  include:
  - if: tag =~ .+
    os: osx
    osx_image: xcode7.3
  - os: linux
    language: python
    python: 2.7
    sudo: required
    services:
    - docker
    addons:
      apt:
        packages:
        - libusb-1.0-0-dev
        - libudev-dev
before_install:
- source contrib/travis/electrum_PAC_version_env.sh
- echo electrum-PAC version is $ELECTRUM_PAC_VERSION
- mkdir -p build && cp contrib/travis/* ./build/ && if [[ $TRAVIS_OS_NAME == 'osx'
  ]]; then ./build/before_install-osx.sh ; else ./build/before_install-linux.sh ;
  fi
install:
- if [[ -z $TRAVIS_TAG ]] && [[ $TRAVIS_OS_NAME == 'linux' ]]; then pip install tox;
  fi
script:
#- if [[ -z $TRAVIS_TAG ]] && [[ $TRAVIS_OS_NAME == 'linux' ]]; then tox; fi
- if [[ $TRAVIS_OS_NAME == 'osx' ]]; then ./build/travis-build-osx.sh ; else ./build/travis-build-linux.sh;
  fi
after_success:
- if [ "$TRAVIS_BRANCH" = "master" ] && [[ -z $TRAVIS_TAG ]] && [[ $TRAVIS_OS_NAME
  == 'linux' ]]; then pip install pycurl requests && contrib/make_locale; fi
deploy:
- provider: releases
  api_key:
    secure: uzEWbVBDu/KZLtWmNWbdD/m9FHzMSiHEogEzTiRcxf/zJ/41mrRyJb13j4VK7TCfxyDC3LjPVR65/VKTaGSl5bXKq8RBBT03fOQqV511fwLkTIdz5vgWbqNNZQJAp4JyCgTLqJaklvE41winMFJzyrI1Ukkq/PKpA+c88xz6NR5fl9EJpnm7JrtIkQAs5P4aGMijUft0hGYpBgd+jMSG1WssRFFaWsg99i3EEn8vkVqPLpCal1WxcfQMUPG9cv8MV6m1jfoPExi/pwFzsD93ZVgjlqnPyqyRrfmZj1tilx2p3xZIjVvwTrDaYsYiVfIfiAPBw2cb4nSBRWVsGD0tITXJ7yzetagnJZoC4Jo8koiU4sfRttlj4XU2cFP4ameF3KhlWXF0NoHcqZ3bC+94QAhh/7T4cE9qi8lhrbcsTy0XAPf93377vH6ZFL1hTe9J9NHtDf5PSH01xVIP0NNaWoAUdDkaso5PL3U1v2D0C9ISco2suALHOby7WJ9PjjGiHq8B1cojUCEdExaXormaYu/khJxgT1p2JouhC8NFYdTYXSsylBqBhdHu9subjuwmst61CXem2wNkTdtCAfMdHx6474bmPyHxxS7WYuYbIcuvIK/Mk2kDnURdPuDBF4o8EF2CqEGCkp2Ue63GpJDH6xB1OgKdPxHcwKGwhfxJulc=
  file:
  - build/electrum-PAC/dist/electrum-PAC-$ELECTRUM_PAC_VERSION-macosx.dmg
  on:
    repo: PACCommunity/electrum-PAC
    tags: true
    condition: "$TRAVIS_OS_NAME = osx"
- provider: releases
  api_key:
    secure: uzEWbVBDu/KZLtWmNWbdD/m9FHzMSiHEogEzTiRcxf/zJ/41mrRyJb13j4VK7TCfxyDC3LjPVR65/VKTaGSl5bXKq8RBBT03fOQqV511fwLkTIdz5vgWbqNNZQJAp4JyCgTLqJaklvE41winMFJzyrI1Ukkq/PKpA+c88xz6NR5fl9EJpnm7JrtIkQAs5P4aGMijUft0hGYpBgd+jMSG1WssRFFaWsg99i3EEn8vkVqPLpCal1WxcfQMUPG9cv8MV6m1jfoPExi/pwFzsD93ZVgjlqnPyqyRrfmZj1tilx2p3xZIjVvwTrDaYsYiVfIfiAPBw2cb4nSBRWVsGD0tITXJ7yzetagnJZoC4Jo8koiU4sfRttlj4XU2cFP4ameF3KhlWXF0NoHcqZ3bC+94QAhh/7T4cE9qi8lhrbcsTy0XAPf93377vH6ZFL1hTe9J9NHtDf5PSH01xVIP0NNaWoAUdDkaso5PL3U1v2D0C9ISco2suALHOby7WJ9PjjGiHq8B1cojUCEdExaXormaYu/khJxgT1p2JouhC8NFYdTYXSsylBqBhdHu9subjuwmst61CXem2wNkTdtCAfMdHx6474bmPyHxxS7WYuYbIcuvIK/Mk2kDnURdPuDBF4o8EF2CqEGCkp2Ue63GpJDH6xB1OgKdPxHcwKGwhfxJulc=
  file:
  - build/electrum-PAC/dist/Electrum-PAC-$ELECTRUM_PAC_VERSION.tar.gz
  - build/electrum-PAC/dist/electrum-PAC-$ELECTRUM_PAC_VERSION-setup.exe
  on:
    repo: PACCommunity/electrum-PAC
    tags: true
    condition: "$TRAVIS_OS_NAME = linux"