sudo: required
language: python
services:
- docker
addons:
  apt:
    sources:
      - sourceline: 'ppa:tah83/secp256k1'
    packages:
      - libusb-1.0-0-dev
      - libudev-dev
      - libsecp256k1-0
matrix:
  include:
  - if: tag =~ .+
    os: osx
    language: ruby
    osx_image: xcode8
  - os: linux
    python: "3.6"
    dist: xenial
  - os: linux
    python: "3.7"
    dist: xenial
before_install:
- source contrib/travis/electrum_PAC_version_env.sh
- echo electrum-PAC version is $ELECTRUM_PAC_VERSION
- mkdir -p build && cp contrib/travis/* ./build/ && if [[ $TRAVIS_OS_NAME == 'osx'
  ]]; then ./build/before_install-osx.sh ; else ./build/before_install-linux.sh ;
  fi
- if [[ -n $TRAVIS_TAG ]] && [[ $TRAVIS_OS_NAME == 'linux' ]] && [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then
      ./build/before_install-linux.sh;
  fi
- if [[ -n $TRAVIS_TAG ]] && [[ $TRAVIS_OS_NAME == 'linux' ]] && [[ $TRAVIS_PYTHON_VERSION == '3.7' ]]; then
      ./build/before_install-linux-apk.sh;
  fi
install:
- if [[ -z $TRAVIS_TAG ]] && [[ $TRAVIS_OS_NAME == 'linux' ]]; then
      pip install tox; pip install tox-travis;
  fi
script:
#- if [[ -z $TRAVIS_TAG ]] && [[ $TRAVIS_OS_NAME == 'linux' ]]; then tox; fi
- if [[ $TRAVIS_OS_NAME == 'osx' ]]; then ./build/travis-build-osx.sh ; else ./build/travis-build-linux.sh;
  fi
- if [[ -n $TRAVIS_TAG ]] && [[ $TRAVIS_OS_NAME == 'osx' ]]; then
      ./build/travis-build-osx.sh ;
  fi
- if [[ -n $TRAVIS_TAG ]] && [[ $TRAVIS_OS_NAME == 'linux' ]] && [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then
      ./build/travis-build-linux.sh;
  fi
- if [[ -n $TRAVIS_TAG ]] && [[ $TRAVIS_OS_NAME == 'linux' ]] && [[ $TRAVIS_PYTHON_VERSION == '3.7' ]]; then
      ./build/travis-build-linux-apk.sh;
  fi
deploy:
- provider: releases
  api_key:
    secure: lzu/ZNdGdgWe2ITNR4ShRKKAjRYVLFnAGL8hOUUYhmvDaJ5xZGYtDq1lBZLc29++l/7yu0iPsgTgP5hSR9kgR19cUiKEGzX8j65hkxPGdItVkhw43gRuQyn1xGRvU/kitaJgcRmpJgEOV1YZKn0Hgjpy8KJmr2cE5tMgQSyiDDofGAKNfUtaVckvjkLkTGYoTTNF7DNK4jYL/TT/8Vox9W6pyJz8eV2sdLyO0Z6GO7/f954yD7Nus8BQNNI7HR9G2bIsNPgsZ23TMPnon2i9f7tgNzzxjeT5Dk1jRwDFeGcAp9K8w3UETIcbtSIVT8tOlC66ejDIfdGnuBj0GUF9eLMlXExjzcUTCjZcz/rdtuLr5gd9ugN1qi9w9CEhiEPEP0moUOTGLEpzR6sv7/rXT8IQTaFPSWUmFIplrXwUXoDRqhvGkwlOF2lWR2AmcND1HxJrOHCU60AzeMiLTvFMtkBNq9IliNjpbLTcpxLjry3JpY7yjuOOTCujnfEOzhw1HzRN+snfAo/OAbK8/dOnSVQNt0G/8nA/IUqZZFnkx50dfdjg7sRT8mjzHbunBfhjsQYI/IZz9BvmCgZmwc+p9k+EW+aG1aWRPcMBOyXbTybj5UVYTKvwHPXhHXJWT2Wi5zkqKOtI+w/6jRVQ3godO0AstUYnjQYJBdwsjZ8RcE0=
  file:
  - build/electrum-PAC/dist/electrum-PAC-$ELECTRUM_PAC_VERSION-macosx.dmg
  on:
    repo: PACCommunity/electrum-pac
    tags: true
    #condition: "$TRAVIS_OS_NAME = osx"
- provider: releases
  api_key:
    secure: lzu/ZNdGdgWe2ITNR4ShRKKAjRYVLFnAGL8hOUUYhmvDaJ5xZGYtDq1lBZLc29++l/7yu0iPsgTgP5hSR9kgR19cUiKEGzX8j65hkxPGdItVkhw43gRuQyn1xGRvU/kitaJgcRmpJgEOV1YZKn0Hgjpy8KJmr2cE5tMgQSyiDDofGAKNfUtaVckvjkLkTGYoTTNF7DNK4jYL/TT/8Vox9W6pyJz8eV2sdLyO0Z6GO7/f954yD7Nus8BQNNI7HR9G2bIsNPgsZ23TMPnon2i9f7tgNzzxjeT5Dk1jRwDFeGcAp9K8w3UETIcbtSIVT8tOlC66ejDIfdGnuBj0GUF9eLMlXExjzcUTCjZcz/rdtuLr5gd9ugN1qi9w9CEhiEPEP0moUOTGLEpzR6sv7/rXT8IQTaFPSWUmFIplrXwUXoDRqhvGkwlOF2lWR2AmcND1HxJrOHCU60AzeMiLTvFMtkBNq9IliNjpbLTcpxLjry3JpY7yjuOOTCujnfEOzhw1HzRN+snfAo/OAbK8/dOnSVQNt0G/8nA/IUqZZFnkx50dfdjg7sRT8mjzHbunBfhjsQYI/IZz9BvmCgZmwc+p9k+EW+aG1aWRPcMBOyXbTybj5UVYTKvwHPXhHXJWT2Wi5zkqKOtI+w/6jRVQ3godO0AstUYnjQYJBdwsjZ8RcE0=
  file:
  - build/electrum-PAC/dist/Electrum-PAC-$ELECTRUM_PAC_VERSION.tar.gz
  - build/electrum-PAC/dist/electrum-PAC-$ELECTRUM_PAC_VERSION-setup.exe
  on:
    repo: PACCommunity/electrum-pac
    tags: true
    #condition: "$TRAVIS_OS_NAME = linux"